server:
  port: 8803
spring:
  application:
    name: spring-cloud-stream-rabbitmq-producer
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 39.97.3.60
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings:
        output:
          destination: exchange_stream
          group: queue_stream
          binder: rabbit # 这里和binders.rabbit对应